### PR TITLE
Added support for various devices

### PR DESCRIPTION
**Pull request by nhassink**
- added doorbell class
- added combined smoke / co / co2 class
- fix in thermostat mode
- Added support for combined temperature/humidity sensors

### CODE REVIEW

**Comment by pimviergever** [comment]
Hi, with the latest dev Homey firmware, all KaKu units are visible in HomeKit via HomeyKit except the wall socket that has the category heating?

**Comment by nhassink** [comment]
Hi, when you give a socket the category heating it become a heating class device in homey. It is not possible to map this correctly to the heater/cooler class in homekit because this has different characteristics then a heating class device in homey. If you want this device to be visible in homekit you could change the category to a standard socket

**Comment by Povlov** [comment]
Humidity info from AeonLabs | Multisensor 6 is not presented. Would be nice!

**Comment by nhassink** [comment]
Hi Povlov. I'm currently working on a rewrite of all sensor type devices. Would you be willing to test my alpha version to check if the humidity info is working in this version? Unfortunately I don't have any humidity sensors myself (yet, still underway from china)

Link to my alpha version: https://github.com/nhassink/com.swttt.homekit/tree/alpha

**Comment by nhassink** [comment]
Hi Povlov, my temperature and humidity sensors came in today. The temperature and humidity information shows in homekit using my latest alpha version.

**Comment by Povlov** [comment]
Hello Niek,

Tx for informing me.
I may need to sideload to test the alpha version.
I have Homey on stable, no sideloads, and even a number of well working
apps on "manual update".
It is pretty rocksolid!! She stutters sometimes, but really the performance
is great, no interruptions or ptp's for weeks on a row.

Good to hear you received your sensors.
The Homeykit runs quite well. There are often red texts below scenes and
devices indicating no connection, failed attempts, but operations do work
when I tap the items.

I have no technical skills, but I do have a very stable home setup with
lights and some a/v items.
Whenever I can be of any help, let me know?


Cheers, Peter.




Peter de Vries

2018-01-30 14:41 GMT+01:00 nhassink <notifications@github.com>:

**Comment by nhassink** [comment]
Hi Peter,

You indeed need to side load the alpha version. But you can always revert back to the stable version later. But I also understand if you don't want to change a good setup.

Niek

**Comment by bonq** [comment]
I have a bunch of Danfoss radiator termostats that does not show up as a device, is there anything I can do to make them?

**Comment by robertklep** [comment]
@bonq no, there's nothing _you_ can do.

The problem is that there's a mismatch between what capabilities HomeKit requires for a thermostat, and the capabilities that the Danfoss app provides for the radiator thermostats. I'll discuss with @nhassink if we want to implement a workaround for that.

I've created a separate issue: #133

**Pull request merged**
