### PR TITLE
Small fix in Light class

### PR DESCRIPTION
**Pull request by nhassink**
small bugfix to fix updates from homey -> homekit for hue lights

### CODE REVIEW

**Comment by robertklep** [comment]
@nhassink looks like you merged a few PR's into your `alpha` branch so this PR (#81) wouldn't have any merge conflicts, is that right?

It would probably be better to keep `alpha`, `beta` and `master` branches in sync with the main repository, and add new features through new branches.

I'm not sure if merging this directly into the main `alpha` branch won't be causing problems, especially since my PR was made against `beta` and not `alpha`.

So what I'd like to propose:
- I'll make sure `alpha` and `beta` on the main repo are in sync, and we can do a new beta release (but see below)
- I'll add the change in `303ef20d3aca89509cecfc10ac786ea3eb056db4` to `alpha`
- I'll change my PR so it's made against `alpha` instead of `beta`
- Either we do an `alpha` release first, or I'll sync up `alpha` with `beta` again. I'm pretty confident my changes (the air pressure sensor) are okay to be released as a `beta` feature

In the future, any changes/new features should be made against `alpha`, and we merge directly to `beta` unless we want to do a real `alpha` release.

**Comment by nhassink** [comment]
I just wanted to check out the new feature you made. So I looked up how to get an unmerged pull request into my own fork. I didn’t realize this could cause issues. So the next time I should pull something like this into a new branch within my own fork?

As for the new feature itself, it seems to work over here so I agree it seems stable enough for beta to me.

**Comment by robertklep** [comment]
@nhassink yeah, it's easier to pull in PR's that you want to test into a separate branch. If you create that branch from `alpha`, it's similar to merging _with_ `alpha`, but since it's on a new branch it won't interfere with the original `alpha` :)

**Comment by robertklep** [comment]
Closing, #81 is now folded into `alpha` through cf54f3dbf79fe52ffeee12b6b69c42d617abafbd

**Pull request closed without merging**
