### PR TITLE
Added 'blinds' with 'windowcoverings_set'-capability support

### PR DESCRIPTION
**Pull request by fishfisher**
The new IKEA Fyrtur blinds have a class of 'blinds' with a capability of 'windowcoverings_set'.

### CODE REVIEW

**Comment by robertklep** [comment]
Thanks! I was actually working on a fix myself, and I took the easy way out:
```
    } else if ([ 'curtain', 'blinds' ].includes(device.class) && 'windowcoverings_set' in capabilities) {
      this.log(`Found ${ device.class } (windowcovering_set): ${ device.name }`);
      isPaired = true;
      bridge.addBridgedAccessory(homekit.createCurtains(device, api));
   }
```

So the same code is used for both blinds and curtains (in Homekit parlance both are "window coverings" anyway).

**Comment by robertklep** [comment]
Just pushed my fix to the beta branch. I realise that I just undone your work, hope you're okay with that 😅

**Comment by fishfisher** [comment]
Hi! Thank god you are here😂 I'm doing my best to get it up and running, but I have about zero experience with this. I'm a decent iOS dev, but this right here is new to me. Thanks for helping out!

**Comment by robertklep** [comment]
I'd be happy to hear how the beta branch is working for you (since I can't test it myself). If it works as expected, I'll try and publish an update tomorrow.

**Comment by fishfisher** [comment]
Thanks! I tried to install the beta branch via CLI, but it doesn't seem to be added. I get the following log message: [log] [HomekitApp] Not adding 'Fyrtur' (shouldn't be paired). Maybe I'm missing something? I can't find it in the 'Devices' list in HomeyKit app in Homey either.

**Comment by robertklep** [comment]
Ah, dangit, I always forget to update the settings page 😬 try again (after pulling the latest commit)

**Comment by fishfisher** [comment]
That was it😊 Works perfectly👍 Awesome job as always!

**Comment by fishfisher** [comment]
Any chance to include ‘measure_battery’ capability as well to get battery state? Probably a bit trickier.

**Comment by robertklep** [comment]
The Window Coverings service in Homekit doesn't support a battery level characteristic, so I don't think that's going to work.

**Comment by fishfisher** [comment]
Makes sense - understood! 👍

**Comment by robertklep** [comment]
I just submitted v3.0.12 (beta) for publication to the app store 😅

**Pull request closed without merging**
