### PR TITLE
"other" sensor support

### PR DESCRIPTION
**Pull request by robertklep**
This change will treat device class "other" the same as device class "sensor". It also allows the capabilities of these devices to be prefixes.

Use case: the MySensors app declares each capability as a prefix, because in theory, a node can have more than one sensor of the same type. So instead of having a capability `measure_temperature`, a device may have a capability `measure_temperature.0`.

This defeated the "capability sniffing" code that Homeykit does, so these capabilities were not exposed to HomeKit. This is now fixed (only for device classes `sensor` and `other`, not sure if it should be implemented for other classes too), and from experience I can say it works just fine.

The PR also removes `lodash` as a dependency, removing a few MB of code. It's replaced by regular JS code, and the standalone `lodash.debounce` package.

### CODE REVIEW

**Comment by swttt** [comment]
not sure if all changes were included with @nhassink his PR, but this is conflicting now.

**Comment by robertklep** [comment]
Merged into `alpha` separately.

**Comment by robertklep** [comment]
@nhassink @denniedegroot @swttt 

Ik heb handmatig #68, #69 en #72 in `alpha` (f343acb) gezet. Zouden jullie even willen checken of de aanpassingen van jullie PR's er goed ingekomen zijn?

**Comment by nhassink** [comment]
Volgens mij wel. Github ziet geen verschillen meer tussen de alpha branch uit mijn fork en de huidige alpha branch.

**Comment by robertklep** [comment]
Thanks! Dan mag @swttt een nieuwe beta publiceren ;)

**Pull request closed without merging**
